### ISSUE TITLE
[BUG] ~ Documentation page shows another library?

### ISSUE THREAD

**Issue by 7ih** [ReplAPI-it/ReplAPI.it-NodeJS#60]
The official documentation page is https://replapi-it.js.org/. When I go to the page, however, it shows the API for the Nextra library: "Nextra is a Next.js based static site generator." https://replapi-it-docs.vercel.app/ has the same problem, too.

Also, the README file has the wrong link for the github issues page.

**Comment by EpicGamer007** [comment]
Yes, I have seen the bug too, Don't know why it shows that.

**Comment by RayhanADev** [comment]
@7ih yeah I need to rewrite documentation but Nextra (the documentation application I use) has been really weird lately and the latest build broke a lot. I need to put up a message somewhere for that xD.

Would you care to open a PR fixing the wrong link :>? I can do it if you're too busy.
