### ISSUE TITLE
[REQUEST] ~ what is the point of the .replapirc file

### ISSUE THREAD

**Issue by 7ih** [ReplAPI-it/ReplAPI.it-NodeJS#63]
When I first installed the package, it installed a .replapirc file with some default initiative values. I feel like it would be fine to remove this file since the values are already set when the server starts, unless there's some weird reason.

**Comment by EpicGamer007** [comment]
i guess it is possible, but it does help with configuration.

**Comment by RayhanADev** [comment]
Heya!

Yeah there is a weird reason the import/export call order is very nit-picky and when we run the program it starts bottom to top so even though you may add the values at the start they aren't read and can't even be used, so we create this config file to balance it out when the program is initialized. My goal is to at some point in time move off early initialization and use config files as standalone but thats not in the foreseeable future.

**Comment by RayhanADev** [comment]
Closing since there was no response.
