### ISSUE TITLE
Use Consistent Configuration File Format

### ISSUE THREAD

**Issue by RayhanADev** [ReplAPI-it/ReplAPI.it-NodeJS#70]
Right now we have` .---rc`'s and `---.config.json`'s and `---.config.js`'s everywhere and frankly it's a pain. We need to use a consistent file format to maintain our configuration files.

I'm opting with `---.config.cjs` since it's most natural.

**Comment by EpicGamer007** [comment]
so no ---.config.mjs or ---.config.js?

**Comment by RayhanADev** [comment]
@EpicGamer007 to clarify, for this repo's configuration files (Babel, Rollup, Prettier, Eslint, etc.) not the package.
